services:
  api:
    build:
      context: ../app/backend
      dockerfile: Dockerfile
    container_name: nightly-api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${RDS_HOST}
      DB_PORT: ${RDS_PORT}
      DB_USER: ${RDS_USER}
      DB_PASSWORD: ${RDS_PASSWORD}
      DB_NAME: ${RDS_DB}

  frontend:
    build:
      context: ../app/frontend
      dockerfile: Dockerfile
    container_name: nightly-frontend
    ports:
      - "3001:3000"
    depends_on:
      - api